### ISSUE TITLE
.gitconfig has your email and name settings

### ISSUE THREAD

**Issue by haideralipunjabi** [adriencarbonaro/dotfiles#2]
I started using your dotfiles a few days ago, and noticed today that all my commits were being listed as yours. It took me a while to figure out that my your git settings had overwritten mine due to `.gitconfig`.

You should either remove them, or add a warning for others

**Comment by adriencarbonaro** [comment]
I don't understand which file is overwriting yours. There is no `.gitconfig` file and `.git/config` doesn't have my credentials.

Could you point out which file ?

**Comment by adriencarbonaro** [comment]
Ah ok you copied the `git/.gitconfig` file. I'll put a warning ! Tanks !
